let VSCodeExtensionStealer = dynamic([
"helper-beeps.solidity-pro",
"helper-beeps.solidity-pro-ai-auditor",
"web3devtoolsx.solidity-pro",
"iktok90-design.solidity-pro"
]);
DeviceProcessEvents
| where Timestamp > ago(30d)
| where InitiatingProcessCommandLine has "\\.vscode\\extensions\\" and InitiatingProcessCommandLine has "code.exe"
| extend ExtensionName = tolower(extract(@"extensions\\([^\\]+)", 1, InitiatingProcessCommandLine))
| where ExtensionName has_any(VSCodeExtensionStealer)