CloudAppEvents
| where TimeGenerated > ago(90d)
| where ipv4_is_in_range(IPAddress, "104.210.140.128/28") or
ipv4_is_in_range(IPAddress, "135.234.64.0/24") or
ipv4_is_in_range(IPAddress, "172.182.193.224/28") or
ipv4_is_in_range(IPAddress, "172.182.193.80/28") or
ipv4_is_in_range(IPAddress, "172.182.194.144/28") or
ipv4_is_in_range(IPAddress, "172.182.194.32/28") or
ipv4_is_in_range(IPAddress, "172.182.195.48/28") or
ipv4_is_in_range(IPAddress, "172.182.209.208/28") or
ipv4_is_in_range(IPAddress, "172.182.211.192/28") or
ipv4_is_in_range(IPAddress, "172.182.213.192/28") or
ipv4_is_in_range(IPAddress, "172.182.224.0/28") or
ipv4_is_in_range(IPAddress, "172.203.190.128/28") or
ipv4_is_in_range(IPAddress, "20.14.99.96/28") or
ipv4_is_in_range(IPAddress, "20.168.18.32/28") or
ipv4_is_in_range(IPAddress, "20.169.6.224/28") or
ipv4_is_in_range(IPAddress, "20.169.7.48/28") or
ipv4_is_in_range(IPAddress, "20.169.77.0/25") or
ipv4_is_in_range(IPAddress, "20.171.123.64/28") or
ipv4_is_in_range(IPAddress, "20.171.53.224/28") or
ipv4_is_in_range(IPAddress, "20.25.151.224/28") or
ipv4_is_in_range(IPAddress, "20.42.10.176/28") or
ipv4_is_in_range(IPAddress, "4.227.36.0/25") or
ipv4_is_in_range(IPAddress, "40.67.175.0/25") or
ipv4_is_in_range(IPAddress, "40.90.214.16/28") or
ipv4_is_in_range(IPAddress, "51.8.102.0/24") or
ipv4_is_in_range(IPAddress, "74.7.175.128/25") or
ipv4_is_in_range(IPAddress, "74.7.228.0/25") or
ipv4_is_in_range(IPAddress, "74.7.228.128/25") or
ipv4_is_in_range(IPAddress, "74.7.229.0/25") or
ipv4_is_in_range(IPAddress, "74.7.229.128/25") or
ipv4_is_in_range(IPAddress, "74.7.230.0/25") or
ipv4_is_in_range(IPAddress, "74.7.241.128/25") or
ipv4_is_in_range(IPAddress, "74.7.242.128/25") or
ipv4_is_in_range(IPAddress, "74.7.243.0/25") or
ipv4_is_in_range(IPAddress, "74.7.244.0/25") or
ipv4_is_in_range(IPAddress, "104.208.184.192/28") or
ipv4_is_in_range(IPAddress, "104.210.139.192/28") or
ipv4_is_in_range(IPAddress, "104.210.139.224/28") or
ipv4_is_in_range(IPAddress, "128.85.198.32/28") or
ipv4_is_in_range(IPAddress, "13.65.138.112/28") or
ipv4_is_in_range(IPAddress, "13.67.72.16/28") or
ipv4_is_in_range(IPAddress, "13.71.2.208/28") or
ipv4_is_in_range(IPAddress, "13.76.116.80/28") or
ipv4_is_in_range(IPAddress, "13.76.32.208/28") or
ipv4_is_in_range(IPAddress, "13.83.167.128/28") or
ipv4_is_in_range(IPAddress, "13.83.237.176/28") or
ipv4_is_in_range(IPAddress, "132.196.82.48/28") or
ipv4_is_in_range(IPAddress, "134.149.233.80/28") or
ipv4_is_in_range(IPAddress, "135.116.136.160/28") or
ipv4_is_in_range(IPAddress, "135.13.64.240/28") or
ipv4_is_in_range(IPAddress, "135.220.73.208/28") or
ipv4_is_in_range(IPAddress, "135.220.73.240/28") or
ipv4_is_in_range(IPAddress, "135.237.131.208/28")
| summarize Count=count() by ActionType
| sort by Count desc 